name: CI Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle build task
        run: ./gradlew check

#      - name: Upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: Archive
#          path: build/libs/actions-test-1.0-SNAPSHOT.jar
#
