# This work flow will build project with Gradle wrapper,
# create a release, and upload contents of ./build/libs/
# to the release.
name: Create or update release

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/heads/release/}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle build task
        run: ./gradlew jar

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          output-file: 'false'
          skip-on-empty: 'true'

      - name: Create release, update, and upload assets
        uses: meeDamian/github-release@v2.0.1
        with:
          tag: ${{ steps.get_version.outputs.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: true
          allow_override: true
          body: |
            ## Changelog for ${{ steps.changelog.outputs.tag }}:
            ${{ steps.changelog.outputs.clean_changelog }}
          files: build/libs/*
          gzip: folders
