# This workflow will create a release on v-tag push

name: "Create release"
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Generate the artifacts
        uses: skx/github-action-build@master
        with:
          builder: './gradlew'

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Changelog for ${{ steps.get_version.outputs.VERSION }} :
            * Change Materials to match Minecraft 1.15
            * Integrated code from local API
            * Add workflows for issue and release creation.
            * Refactored main class
            * Change how plugin watches for eggs to hatch
            * Change ProjectileHitEvent: getBlock location -> getEnttity location
            * Changed Config library to Lightning Storage
          files: build/libs/BreedablePets.jar
          gzip: folders

