name: Changelog
on:
  pull_request:
    types: [closed]
  release:
    types: [published]
  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v2.4.0
        with:
          # Github token
          github-token:
          # Commit message to use
          git-message: Update changelog {version}
          # Number of releases to preserve in changelog
          release-count: # optional, default is 5
          # The path to the package.json to use
          package-json: # optional, default is ./package.json
