name: "Build and upload artifact"
on:
  push:
    branches:
      - 'dev'
defaults:
  run:
    shell: bash
    working-directory: $GITHUB_WORKSPACE
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Build project"
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
        with:
          args: build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v1
        with:
          name: BreedablePets-JAR
          path: build/libs/
