name: "Build and upload artifact"
on:
  push:
    branches:
      - 'dev'
defaults:
  run:
    shell: bash
    working-directory: $GITHUB_WORKSPACE
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Setup Java
        used: actions/setup-java@v1
        with:
          java-version: 8

      - name: Generate the artifacts
        uses: skx/github-action-build@master
        with:
          builder: './gradlew'

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/libs/BreedablePets.jar'
