# This workflow will build the project JAR
# and make it available to download.

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle build task
        run: ./gradlew check

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Archive
          path: build/libs/actions-test-1.0-SNAPSHOT.jar

